language: node_js
node_js: '8'
deploy:
  provider: heroku
  api_key:
    secure: LpAGXFgcLWrP37lyx/trA69YbUcwciHmWj0rsVSgbjjdZMkgCMtxdnlcKtKLNzbKScMc0rathzoa2rFddhsICVeBbQUj+PoAK9KDSU2AW2MThYxfnTozGz5ELmx7Y5ZBI7ys3FK/wCNx+144vK51hTpIlM59uipd9UIPd+HdNc5D/K89sHtCCu56EHljoZFjCA5we+5biyOohAYZmoAxS9uQuv5tnIcLcIPltk0GXnJ9hNCN8lizDliEOepVHMBR0yNQIFWgFoivNvLHknZBiSqF1TBaRLgv39pzYwiqXhzl7k9n8xJzgWWbEa8zRNRNYh5AA7f2P1nQcyeaG4nR4pR5fS0W5ewwgDNme7DQoV0h5WG+V5WDv/WCW/ALkIyVCWgwFakm1U/NKcuyZzTPCtw25a6LTxH2sTDRy2LU+wSYBdUl3jDFSQruL6lr1EY5ryQ/Cy2cq3RPEFSbRmDkGKdJgtSJb0Q6RqqAAEHNh9n6r+ZFVZPC2Uv/sYgounwr59isL6IErsn+mC2nLK8IhURgYhK6j+FbwGtTmAA/UAH+MJ6kGc1icY+rCENawsoZnmIezoJt7yXj9zeQXM2H+SfwzgB7j7nJLnAPUMs/5VsibeVhYMxrcVOj5lT31gtFoFXf51w7ZiSDBDA9N1CzOquDtBLv7Cd0HFGV8yIGcuA=
  app: ultiscorer
  on:
    repo: LukeSheard/ultiscorer
